[package]
name = "host-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
vsock = "0.5.0"
log = "0.4"
env_logger = "0.11.3"
colored = "2.1.0"
vsock-protocol = { path = "../vsock-protocol" }
cmio = { path = "../guest-agent/crates/cmio", features = ["mock_cmio"] }


[[bin]]
name = "host-agent"
path = "src/main.rs"

[lib]
name = "host_agent"
path = "src/lib.rs" 
