[package]
name = "guest-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
cmio = { path = "crates/cmio" }
libc = "0.2"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
colored = "2.1.0"
vsock = "0.5.0"
vsock-protocol = { path = "../vsock-protocol" }

[[bin]]
name = "guest-agent"
path = "src/main.rs"

[lib]
name = "guest_agent"
path = "src/lib.rs" 