[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
cartesi-machine = { git = "https://github.com/zippiehq/cm-rust-bindings", rev = "b6b245e5df16a7f9e4e2ff33c5eaad90778d7cfb", features = ["download_uarch"] }
log = "0.4"
env_logger = "0.10"
colored = "2.1.0"
vsock = "0.5.0"
vsock-protocol = { path = "../vsock-protocol" }
hyper = { version = "1.6.0" }
hyper-util = { version = "0.1", features = ["tokio", "server", "http1"] }
http-body-util = "0.1"
bytes = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }

[[bin]]
name = "runner"
path = "src/main.rs"
