[package]
name = "cmio"
version = "0.1.0"
edition = "2021"

[features]
mock_cmio = []

[dependencies]
libc = "0.2"
thiserror = "1.0"
nix = { version = "0.27", features = ["ioctl"] }
vsock-protocol = { path = "../../../vsock-protocol"}

[lib]
name = "cmio"
path = "src/lib.rs" 